Bootstrap: docker
From: julia:1.0

%environment
	JULIA_DEPOT_PATH=/mnt/storage/.julia
	PYTHON=/usr/lib/x86_64-linux-gnu/
  export JULIA_DEPOT_PATH
  export PYTHON
  export XDG_RUNTIME_DIR=""
  export DISPLAY=:0

%runscript
  export JULIA_NUM_THREADS="$(( `nproc` / 2 ))"
  exec xvfb-run --auto-servernum /usr/local/julia/bin/julia -O 3 --project "$@"

%post
	apt update
	apt install -y python3 python3-pip \
		ssh vim \
		ffmpeg hdf5-tools libcairo2 pdf2svg imagemagick \
		libczmq-dev cmake xorg-dev dvipng libxt6 libxrender1 \
		mesa-utils libxrandr-dev libxinerama-dev libxcursor-dev \
		libgl1-mesa-glx libqt5widgets5 xvfb

	# JuptyerLab (experimental)
  pip3 install jupyterlab

  # LaTeX
  apt install -y texlive-latex-base \
		texlive-latex-recommended \
    texlive-luatex \
    texlive-generic-extra \
    texlive-science
