Bootstrap: docker
From: julia:1.0

%environment
	JULIA_DEPOT_PATH=/mnt/storage/.julia
	PYTHON=/usr/lib/x86_64-linux-gnu/
        export JULIA_DEPOT_PATH
	export PYTHON
        export XDG_RUNTIME_DIR=""
	export DISPLAY=:0

%runscript
        export JULIA_NUM_THREADS="$(( `nproc` / 2 ))"
        exec /usr/local/julia/bin/julia -O 3 "$@"

%post
	apt update
	apt install -y python3 python3-pip \
		ssh vim \
		ffmpeg hdf5-tools libcairo2 pdf2svg imagemagick \
		libczmq-dev cmake xorg-dev \
		mesa-utils libxrandr-dev libxinerama-dev libxcursor-dev

	# Other dependencies
#        yum -y install gettext-libs gsl-devel

        # Python
#        dnf -y install python3-numpy python3-scipy python3-matplotlib python3-ipython \
#                python3-pandas python3-sympy python3-nose atlas-devel notebook

	# JuptyerLab (experimental)
        pip3 install jupyterlab

        # LaTeX
        apt install -y texlive-latex-base \
		texlive-latex-recommended \
                texlive-luatex \
                texlive-generic-extra \
                texlive-science

	# MS fonts
	echo \
"deb http://deb.debian.org/debian stretch main contrib non-free
deb-src http://deb.debian.org/debian stretch main contrib non-free

deb http://security.debian.org/debian-security/ stretch/updates main contrib non-free
deb-src http://security.debian.org/debian-security/ stretch/updates main contrib non-free

deb http://deb.debian.org/debian stretch-updates main contrib non-free
deb-src http://deb.debian.org/debian stretch-updates main contrib non-free" \
	> /etc/apt/sources.list
	apt update
	apt install -y msttcorefonts

