Bootstrap: docker
From: fedora:latest

%environment
	JULIA_PKGDIR=/mnt/singularity/.julia
	export JULIA_PKGDIR

%runscript
	exec /usr/bin/julia "$@"

%post
	yum -y groupinstall "Development Tools"
	yum -y install which bzip2
	yum -y install gcc gcc-c++ make cmake openmpi openmpi-devel
	yum -y install yum-utils
	dnf -y install copr-cli
	dnf -y install dnf-plugins-core
	dnf -y copr enable dperson/neovim
	dnf -y install neovim
	echo "Installing LaTeX"
	yum -y install texlive-scheme-gust
	yum -y install texlive-scheme-tetex
	yum -y install texlive-collection-latexextra
	yum -y install texlive-collection-genericextra
	yum -y install texlive-collection-publishers
	yum -y install texlive-collection-mathextra
	yum -y install texlive-collection-pictures
	yum -y install texlive-collection-science
	yum -y install texlive-ctablestack
	yum -y install texlive-collection-luatex
	echo "Installing Python"
	dnf -y install python3-numpy python3-scipy python3-matplotlib python3-ipython python3-pandas python3-sympy python3-nose atlas-devel notebook
	dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
	dnf -y install ffmpeg
	echo "Installing julia"
	dnf -y copr enable nalimilan/julia
	yum -y install julia
	yum -y install cairo gtk3 ImageMagick
	yum -y install hdf5
	dnf -y install czmq-devel
	yum -y install pdf2svg

